# Generated by Django 5.2.7 on 2025-11-04 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='phone',
            field=models.CharField(null=True, verbose_name='Email'),
        ),
    ]
